# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm6375-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter peux stone veux,$(TARGET_DEVICE)),)

endif
